networks:
  traefik:
    name: traefik-net
    external: true

services:
  app1:
    image: nginx
    volumes:
      - "./app1/public:/usr/share/nginx/html"
      - "./app1/default.conf:/etc/nginx/conf.d/default.conf"
      #- "./app1/m301.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.app1_route.entrypoints=websecure
        - traefik.http.routers.app1_route.tls=true
        - traefik.http.routers.app1_route.tls.certresolver=myresolver
        - traefik.http.routers.app1_route.rule=Host(`test-app1.terrazo.at`)
        - traefik.http.routers.app1_route.service=app1
        - traefik.http.services.app1.loadbalancer.server.port=80

  app2:
    image: nginx
    volumes:
      - "./app2/public:/usr/share/nginx/html"
      - "./app2/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.app2_route.entrypoints=websecure
        - traefik.http.routers.app2_route.tls=true
        - traefik.http.routers.app2_route.tls.certresolver=myresolver
        - traefik.http.routers.app2_route.rule=Host(`test-app2.terrazo.at`)
        - traefik.http.routers.app2_route.service=app2
        - traefik.http.services.app2.loadbalancer.server.port=80
