services:
  app1:
    image: nginx
    volumes:
      - "./app1/public:/usr/share/nginx/html"
      - "./app1/default.conf:/etc/nginx/conf.d/default.conf"
      #- "./app1/m301.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8090:80"
  app2:
    image: nginx
    volumes:
      - "./app2/public:/usr/share/nginx/html"
      - "./app2/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8091:80"